# BL40A2010 Introduction to IoT-Based Systems

## Assignment 6, 22.10.2020

### Author: Niki Malmsten

**Prisoner's dilemma** is a standard example of a game analyzed in game theory that shows why two completely rational individuals might not cooperate, even if it appears that it is in their best interests to do so. It was originally framed by Merrill Flood and Melvin Dresher while working at RAND in 1950. Albert W. Tucker formalized the game with prison sentence rewards and named it "prisoner's dilemma", presenting it as follows:

"Two members of a criminal gang are arrested and imprisoned. Each prisoner is in solitary confinement with no means of communicating with the other. The prosecutors lack sufficient evidence to convict the pair on the principal charge, but they have enough to convict both on a lesser charge. Simultaneously, the prosecutors offer each prisoner a bargain. Each prisoner is given the opportunity either to betray the other by testifying that the other committed the crime, or to cooperate with the other by remaining silent. The possible outcomes are:

- If A and B each betray the other (not-cooperating to each other), each of them serves $z$ years in prison (payoff of $-z$)
- If A betrays B (not-cooperating with B) but B remains silent (cooperating with A), A will serve $y$ years in prison (payoff $-y$) and B will serve $w$ years  (payoff of $-w$).
- If B betrays A (not-cooperating with A) but A remains silent (cooperating with B), B will serve $y$ years in prison (payoff $-y$) and A will serve $w$ years  (payoff of $-w$).
- If A and B both remain silent, both of them will serve $x$ years in prison (payoff of $-x$)."

The payoff table is presented below. 

|                | $B$ cooperates  | $B$ not-cooperating   |
|----------------|:---------------:|--------------:|
| $A$ cooperates |  $A \rightarrow -x$   | $A\rightarrow -w$  |
|                |  $B\rightarrow -x$   | $B\rightarrow -y$  |
|                |                 |               |
| $A$ not-cooperating   |  $A\rightarrow -y$   | $A\rightarrow -z$  |
|                |  $B\rightarrow -w$   | $B\rightarrow -z$  |

**However, this is only a *Prisoner's Dilemma GAME* for A GIVEN RELATION between the years in prison (payoffs) as to be studied next.**

ps. Text adapted from [Wikipedia](https://en.wikipedia.org/wiki/Prisoner's_dilemma).

**(1) Consider the Prisoner's dilemma description given above.**

**(a) What is the relation between the payoffs values $x\geq 0$, $y\geq 0$, $w\geq 0$ and $z \geq 0$ so that the game can be classified as [Prisoner's Dilemma](https://en.wikipedia.org/wiki/Prisoner's_dilemma)?**

**(b) Verify the results (i.e., the proposed inequality) with numerical examples using [nashpy](https://nashpy.readthedocs.io/en/stable/index.html). Please provide one example when the inequality holds and one it does not (check my example for Dove and Hawyk game).**

In [1]:
pip install nashpy

     |████████████████████████████████| 14.5 MB 4.4 MB/s eta 0:00:01
     |████████████████████████████████| 25.9 MB 39.4 MB/s eta 0:00:01
  Created wheel for nashpy: filename=nashpy-0.0.19-py3-none-any.whl size=10814 sha256=96513763045143dcdb504263bb363f8afff5184a038911c3634c6ead45204752
  Stored in directory: /home/jovyan/.cache/pip/wheels/8e/b8/e4/255ea14bf12a196a4d0e934124c2dfc26d6e4d1111e5c271d3
Successfully built nashpy
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
import nashpy as nash

In [3]:
a.) cooperation is better than not cooperating, so x > z
if only other does not cooperate, it results to a reward, so y > w
when out together x > y > z > w
x = 1
z = 3
y = 2
w = 5

SyntaxError: invalid syntax (<ipython-input-3-971e14f770e6>, line 1)

In [21]:
# with these values the result will be inequal, so it's logical to not cooperate, but
# the best solution is still to cooperate. This would make the game prisoners dilemma
A = [[1, 5], [2, 3]]
B = [[1, 2], [5, 3]]
prisoner = nash.Game(A, B)
prisoner

Bi matrix game with payoff matrices:

Row player:
[[1 5]
 [2 3]]

Column player:
[[1 2]
 [5 3]]

In [22]:
eqs = prisoner.support_enumeration()
list(eqs)

[(array([1., 0.]), array([0., 1.])),
 (array([0., 1.]), array([1., 0.])),
 (array([0.66666667, 0.33333333]), array([0.66666667, 0.33333333]))]

In [15]:
# with these values the result will be equal, there isn't a big reward to not cooperate
# or to cooperate, but ther best solution still remains for both to cooperate. This is
# still prisoners dilemma game
A = [[1, 4], [2, 3]]
B = [[1, 2], [4, 3]]
prisoner = nash.Game(A, B)
prisoner

Bi matrix game with payoff matrices:

Row player:
[[1 4]
 [2 3]]

Column player:
[[1 2]
 [4 3]]

In [16]:
eqs = prisoner.support_enumeration()
list(eqs)

[(array([1., 0.]), array([0., 1.])),
 (array([0., 1.]), array([1., 0.])),
 (array([0.5, 0.5]), array([0.5, 0.5]))]

In [17]:
# with these values the game will change and logical result is not to cooperate.
# this is not a prisoners dilemma game
A = [[2, 4], [1, 3]]
B = [[2, 1], [4, 3]]
prisoner = nash.Game(A, B)
prisoner

Bi matrix game with payoff matrices:

Row player:
[[2 4]
 [1 3]]

Column player:
[[2 1]
 [4 3]]

In [18]:
eqs = prisoner.support_enumeration()
list(eqs)

[(array([1., 0.]), array([1., 0.]))]

**(2) Justify why the game from the previous exercise is or is not a good (reasonable) model when $A$ and $B$ are:**

**1. Two trained members from the army when they are in prison.**
I assume that people who have army training will be silent, meaning they will cooperate, which would make the game not a good model because they would always cooperate. But if them being soldiers doesen't matter it would be a good model, because being scared that the other one would not cooperate could cause the other to not cooperate either.

**2. Competitive companies in the market discussing standardization.**
I think it's almost a good model, when the companies cooperate, they both gain from it and can strategize, but if the other doesen't cooperate it wins the competion and could gain everything and if both don't cooperate it's the 3rd worst solution. So if only the other does not cooperate it wins more then if they both cooperate.

**3. Two different autonomous IoT-based home energy management algorithms that are focus on energy efficiency.**
The goal is energy efficiency, so there is no reason to not work together, they both get the best outcome whne they work together.

**4. Two different autonomous IoT-based home energy management algorithms that are focus on profit maximization.**
I think the prisoners dilemma is an ok model, because if they cooperate they both win by making a better service that could cost more, if only other cooperates the other gets a better service meaning more money so the other one doesen't get that much, if neither cooperate they can't charge that much for the service. But in the ned I don't see huge reasons for cooperation, because it propably wouldn't generate much more money.


**ps. You need to think about the assumption used in Game Theory and in the Prisoner's dilemma problem setting.**